### PR TITLE
add `msglm`

### PR DESCRIPTION
**Pull request by comhar**
This PR integrates [msglm](https://pypi.org/project/msglm/) 🚀

### CODE REVIEW

**Comment by jph00** [comment]
Thanks @comhar !

**Comment by comhar** [comment]
> Thanks @comhar !

No problem. 

Quick followup note. 
I noticed that cache usage or at least cache usage reporting appears to be broken. Basically when we set `cache=True`, the cache writes and reads returned by `.use` remain at 0. This is unrelated to the `msglm` integration. I'll take a closer look and push a PR when I get a chance.

**Comment by jph00** [comment]
Thanks! It definitely used to work at some point...

**Comment by comhar** [comment]
> > Thanks @comhar !
> 
> No problem.
> 
> Quick followup note. I noticed that cache usage or at least cache usage reporting appears to be broken. Basically when we set `cache=True`, the cache writes and reads returned by `.use` remain at 0. This is unrelated to the `msglm` integration. I'll take a closer look and push a PR when I get a chance.

I created a [gist](https://gist.github.com/comhar/8f5dc03879787d0ad43ca9571875e6db) that demonstrates that caching is still working. 

What I initially thought might have been a bug, was probably me using a prompt that didn't exceed 1024 tokens and as a result so Claude didn't cache it.

**Pull request merged**
