### PR TITLE
Save all messages in client.log[]

### PR DESCRIPTION
**Pull request by xl0**
@jph00 Sorry it took so long, here is the revised version.

### CODE REVIEW

**Comment by xl0** [comment]
@jph00 Can we also set cell_number = False?

**Comment by jph00** [comment]
Sure go for it!

**Comment by xl0** [comment]
@jph00 Done

**Comment by jph00** [comment]
Looks good! How about making it optional, defaulting to False, since most people will use the Chat class with already stores history?

**Comment by xl0** [comment]
Initially, I considered it but decided against making it optional because I did not see a downside to keeping the logs.
But on second thought, if you use the same client over and over, and you are sending lots of base64 encoded images, I can see a scenario where the memory load would become significant.

Let me make it conditional.

**Comment by xl0** [comment]
@jph00 Done

**Comment by jph00** [comment]
Thank you!

**Pull request merged**
