### PR TITLE
Logs

### PR DESCRIPTION
**Pull request by xl0**
This adds logs support, with nice formatting and accounts for tool use and images.

I also switched repr to use HTML tags for lists, as mixing tags and markdown is finicky.

This is on top of PR #12 
image

### CODE REVIEW

**Comment by xl0** [comment]
I just checked in Jupyter, and <details> is not rendered with a triangle. Also, all outputs saved in vscode appear as plain text for some reason...
image

**Comment by xl0** [comment]
`<summary style="display: list-item">Summary</summary>` gets the triangle back both in nbclassic and in vscode.

I ran into a weird issue - when I close and open the notebook, all the markdown cells are not rendered properly in nbclassic (vscode is fine). I switched _repr_markdown_ to _repr_html_, and the formatting persists across kernel shutdown and nbdev_clean.

**Comment by jph00** [comment]
I'm not sure about this one -- it's quite a lot of extra code, and I'm not sure if it's needed. I wonder if there might be some way to make this available as a separate plugin in something? Maybe we could add some kind of extensibility you could plug in to?

**Comment by xl0** [comment]
I think adding the logs must be part of the core, but the display part can be patched in. That said, I found it indispensable when debugging my code that uses the library.

**Comment by jph00** [comment]
> I think adding the logs must be part of the core

Agreed - would you be open to adjusting this so that just the minimal is needed in the lib for you to add the display externally?

**Comment by xl0** [comment]
Ok, can do

**Comment by xl0** [comment]
@jph00 Could you please push a release with the other PR? This once might take me a day or two, but I'll need to include the new Claudette version as a dependency for another project, and it needs the stop sequence to work.

**Comment by jph00** [comment]
Done.

**Comment by xl0** [comment]
Thank you!

**Comment by jph00** [comment]
@xl0 I'm going to close this -- might be easiest to open a new PR with the logs functionality, if that's OK.

**Pull request closed without merging**
