### PR TITLE
Add ability to return function outputs

### PR DESCRIPTION
**Pull request by ncoop57**
This PR adds a flag to add to the chat object which when set will return the direct outputs from the function calling api back to the user. This is especially useful when wanting to constrain the model to a specific format.

Also added an example on how to do this for a relatively complex data format:

```python
class Turn:
    """A turn between an assistant and a user."""
    def __init__(
        self,
        user: str, # The user's message
        assistant: str, # The assistant's message
    ):
        store_attr()

    __repr__ = basic_repr(('user', 'assistant'))

class Conversation:
    """A conversation between an assistant and a user."""
    def __init__(
        self,
        turns: List[Turn] # A list of `Turn` objects
    ):
        store_attr()

    __repr__ = basic_repr(('turns'))

sp = "Never mention what tools you use."
chat = Chat(
    model,
    sp=sp,
    tools=[Conversation],
    tool_choice='Conversation',
    return_func_output=True
)
r, func_outputs = chat('Create a conversation between a python programmer and a rust programmer')
print(func_outputs[0][1])
# OUTPUT:
# __main__.Conversation(turns=[{'speaker': 'Python Programmer', 'text': "Hey there! I heard you're a Rust programmer. How do you like working with Rust?"}, {'speaker': 'Rust Programmer', 'text': "Hi! I love working with Rust. The performance and safety features are amazing. How about you? What's your experience with Python?"}, {'speaker': 'Python Programmer', 'text': "Python is great! It's so easy to write and read. I can prototype ideas quickly. But I've heard Rust is really fast. How does it compare in terms of development speed?"}, {'speaker': 'Rust Programmer', 'text': "That's true, Rust has a steeper learning curve compared to Python. The compile-time checks can slow down initial development, but they catch a lot of bugs early. How do you handle concurrency in Python?"}, {'speaker': 'Python Programmer', 'text': "We use libraries like asyncio for concurrent programming. It's pretty straightforward, but I've heard Rust's approach is different. How does Rust handle concurrency?"}, {'speaker': 'Rust Programmer', 'text': "Rust's ownership model and borrowing rules make concurrent programming much safer. We rarely encounter data races. But I do miss Python's extensive library ecosystem sometimes. How's the package management in Python these days?"}, {'speaker': 'Python Programmer', 'text': "Package management with pip and virtual environments works well for us. What about Rust? I've heard good things about Cargo."}, {'speaker': 'Rust Programmer', 'text': "Cargo is fantastic! It handles dependencies, building, and testing all in one tool. It's one of Rust's strong points. Do you ever find Python's dynamic typing to be a challenge in large projects?"}, {'speaker': 'Python Programmer', 'text': "Sometimes, yes. We use type hints to mitigate that, but it's not the same as Rust's static typing. I suppose that's one area where Rust shines, right?"}, {'speaker': 'Rust Programmer', 'text': "Absolutely! The static typing in Rust catches so many potential issues at compile-time. It's a real confidence booster. But I have to admit, I sometimes miss the simplicity of Python for quick scripts and data analysis."}])

```

`func_outputs` is a list of tuples with the first entry of each tuple being the tool id and the second being the output of the tool.

### CODE REVIEW

**Comment by jph00** [comment]
Looking like a nice direction @ncoop57! Minor: how about removing the `return_` prefix?

Do we really need to return a tuple? It seems odd to me that we already have an object with the ids and the results, and we create a whole separate one in a slightly different format! The difference other than structure is that one is stringified, right?

Maybe instead we shouldn't stringify, but instead when we submit a message we should stringify any non-string values?

Does your solution work correctly when following up in the chat? AFAICT it won't work correctly, because you're passing the tool result back to the model - but we don't actually want to do that do we? There isn't really a tool result, because it's not a real tool. Either way, make sure you've done lots of testing and let me know what you've checked.

**Comment by ncoop57** [comment]
Yes i agree it is a bit funky that there is a stringified version and an non stringified version since we can't have complex objects in the 'content' variable. Sadly, we do need to provide a 'tool_result' message. Me and Faisal attempted many ways to avoid this but anthropic requires every tool use block to be accompanied by a tool result message. This current implementation will allow for follow up messages, me and faisal did a number of examples to ensure that would be consistent.

Originally we had planned on having a separate response model and way of explicitly asking the model for this type of tool calling. However it seems unintuitive and brought up a bunch of other issues since we actually have to have the tools be persistent across the chat. We can't just introduce a tool halfway through the chat and not continue to have it afterwards.


I also wanted to go this way as I thought there may be other cases in which you would like the output of the tool call to be returned and not stringified. You can always reconstruct the function call yourself by parsing the tool use block message and generate the output but that would be running the tool twice. Doing this and allowing users access to the true tool output then allowed for this special case of using it for structured outputs.

Happy to discuss more on the design for this feature.

**Comment by ncoop57** [comment]
Faisal and I also tried just changing what the tool result message was such as "response model was successful created" but that seemed to be messy too much with the chat history without the user knowing. Another thing we could do is modify the __str__ of these python classes to return something less verbose as the tool result.

**Comment by ncoop57** [comment]
This PR is superseded by #28

**Pull request closed without merging**
