### PR TITLE
Default chat prompt & function calling refactor

### PR DESCRIPTION
**Pull request by tom-pollak**
@jph00 core changes from #14 here

Added a `cont_pr` param to Chat as a "default" prompt

This fixes the user,assistant,user role loop in cases where the prompt
is not provided (e.g. `chat()`) the `cont_pr` prompt is injected
instead.

`cont_pr` is None by default, so keeps the same behaviour as before
(throw an error)

---

Refactored call_func into two seperate functions:

- `call_func` same as before, but instead returns raw function result
- `mk_funcres` takes raw function result and `tool_use_id` to create a chat message

this isn't necessary for claudette but is quite small and useful for my pydantic integration

### CODE REVIEW

**Comment by tom-pollak** [comment]
@jph00 pydantic support here https://github.com/tom-pollak/claudette-pydantic

Longer example:
https://github.com/tom-pollak/claudette-pydantic/blob/main/nbs/examples/pet_store.ipynb

**Comment by jph00** [comment]
Great job @tom-pollak ! Mentioned it here:
https://x.com/jeremyphoward/status/1820210875388833985

**Comment by tom-pollak** [comment]
Thanks @jph00! Do you mind triggering another pypi release so claudette-pydantic can use it as a dep?

**Comment by jph00** [comment]
Done @tom-pollak

**Pull request merged**
